const actionTypes = {
    OPEN_DIALOG: 'OPEN_DIALOG',
    CLOSE_DIALOG: 'CLOSE_DIALOG',
    CLOSE_CLEAR_DIALOG: 'CLOSE_CLEAR_DIALOG',
    LOAD_THINGS: 'LOAD_THINGS',
    SAVE_THING: 'SAVE_THING',
    NAVIGATE: 'NAVIGATE',
    DIALOG_THING_CHANGE: 'DIALOG_THING_CHANGE',
    DIALOG_DATA_CHANGE: 'DIALOG_DATA_CHANGE',
    FILTER_WHEN_CHANGED: 'FILTER_WHEN_CHANGED',
    CHANGE_ID: 'CHANGE_ID'
};

export default actionTypes;